version: "3.8"

services:
  pwa-showcase:
    image: ghcr.io/splatcrafter/parver-pwa-test:latest
    ports:
      - "41990:8080"
    environment:
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY:-}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY:-}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
